### ISSUE TITLE
License for PyBasic?

### ISSUE THREAD

**Issue by swinslow** [richpl/PyBasic#1]
Hi @richpl, thanks so much for creating PyBasic! I'm setting up an old laptop for my niece to teach her programming the way I first learned it about 30 years ago, and this looks perfect to use for an interpreter.  :)

I was wondering, is there a particular open source license for PyBasic? I'm happy to submit a PR to add one (whichever you would prefer, GPLv2/v3 or MIT or anything else in between), just wanted to make sure there was a license also in case I come across issues to submit PRs for. Thank you again!

**Comment by richpl** [comment]
Hi @swinslow, I'm flattered and humbled that you want to use PyBasic to teach your niece, thanks for the shout out.

I was pretty relaxed about licensing so didn't do anything about it, but very happy to receive a PR to add one. I would support something very permissive, such as GPLv3 I guess.

I suspect that you might be stress testing the software more than I have. Please let me know any issues, though I've moved on to other projects and haven't touched this for over a year. So I don't know how quickly I might get around to fixing anything!

**Comment by swinslow** [comment]
Thanks @richpl! Sounds great. Just a quick note that GPLv3 is usually considered strong copyleft rather than permissive (something like MIT is usually considered permissive), but I'm perfectly happy for it to be GPLv3. I'll send you a PR shortly to add GPLv3 and you can merge it if you're good with it.

And no worries about feeling like you need to fix anything, if I do find any issues! No intention to put work on your plate  :)  I'll take a first go at solving anything that I do come across.
