### ISSUE TITLE
Logical operators?

### ISSUE THREAD

**Issue by JiFish** [richpl/PyBasic#11]
How do you feel about adding the logical operators AND, OR, NOT and XOR? Even though there's no bools proper, this would be useful for compacting IF statements.

I'd like to do this how locomotive BASIC and similar dealt with it. Logical and Relationship operators are treated the same as arithmetic operators with the order of operations: logical, relationship, addition/sub, multiplication/div. Logical and relational operators output 1 for true, 0 for false. Logical operators treat non-0 inputs as true.

**Comment by richpl** [comment]
I'm torn about this one. As you say, there are no booleans so it feels a bit awkward, although I know Perl makes a similar compromise.

**Comment by JiFish** [comment]
Yeah, I can understand your reluctance on this one. Ultimately, it is down to you.

But if it strengthens the case, this is how most versions of BASIC have dealt with it since 1980. Sort of...

MS BASIC variants like Commodore BASIC, locomotive etc. returned -1 and 0 from relational operators. Logical operators converted to an integer and did a bitwise operation. I did suggest something a bit more like Perl for the sake of keeping it simple. But it adds up to the same functionality.

As an alternative, you can sort of achieve this already with some tricks.
```
10 REM A IS TRUE (1)
20 A = 9 < 10
30 REM B IS FALSE (0)
40 B = 9 = 10
50 REM LOGICAL OR
60 PRINT IF$ ( ( A + B ) > 0 , "TRUE" , "FALSE" )
70 REM LOGICAL AND
80 PRINT IF$ ( ( A + B ) = 2 , "TRUE" , "FALSE" )
90 REM LOGICAL XOR
100 PRINT IF$ ( ( A - B ) <> 0 , "TRUE" , "FALSE" )
```
