### ISSUE TITLE
Bug in Interpreter.py

### ISSUE THREAD

**Issue by Nerun** [richpl/PyBasic#16]
In line 108, change:
<code>file=stderr</code>

To:
<code>file==stderr</code>

Interesting program, good job!

**Comment by JiFish** [comment]
`file=stderr` is a [keyword argument](https://docs.python.org/3/tutorial/controlflow.html#keyword-arguments) and is correct. In this case it's telling print to output to [stderr](https://en.wikipedia.org/wiki/Standard_streams#Standard_error_\(stderr\)).

Is it not working for you?

**Comment by Nerun** [comment]
No, is not working for me. But when changed as explained, it works! Python 3.7.3 here, don't know if matters.

**Comment by JiFish** [comment]
Working fine for me in the same version.

The change you made disables outputting to stderr, so perhaps the problem is stderr is not available in your environment. What OS are you running python under? Is any error message thrown?

Outputting to stderr is not essential. If that is the problem, it might be possible to detect stderr isn't available and use stdout instead.

**Comment by Nerun** [comment]
Curious. Running Debian 10.7 on arch x86_64. No error message. Except for stderr. Will run it again later to show to you.

**Comment by JiFish** [comment]
Another possibility: do you have python 2 installed in addition to python 3? Many distributions provided both up until recently.

If you're accidentally running in python 2.x it will error in that exact position:
```
  File "interpreter.py", line 108
    print("Unrecognised input", file=stderr)
                                    ^
SyntaxError: invalid syntax
```

**Comment by Nerun** [comment]
> Another possibility: do you have python 2 installed in addition to python 3? Many distributions provided both up until recently.
> 
> If you're accidentally running in python 2.x it will error in that exact position:
> 
> ```
>   File "interpreter.py", line 108
>     print("Unrecognised input", file=stderr)
>                                     ^
> SyntaxError: invalid syntax
> ```

ABSOLUTELY RIGHT! I was running it on Python 2.7.16. In 3.7.3 it works! Sorry for any inconvenience, closing issue.

**Comment by JiFish** [comment]
No inconvenience, glad you got it sorted. 👍
