### ISSUE TITLE
Ctrl-D improvement suggestion

### ISSUE THREAD

**Issue by Nerun** [richpl/PyBasic#17]
Hi again,

I know there is an "exit" command, but Ctrl-D is frequently used as an exit. You could add an extra try/except:

interpreter.py:
```
while True:
    stmt = input('> ')
```
Typical exit with Ctrl-D:
![ctrld](https://user-images.githubusercontent.com/3987342/107133779-935d9b80-68ca-11eb-90d6-6a92a1f9e76c.png)

For a beautiful exit:
```
while True:
    try:
        stmt = input('> ')
    except EOFError:
        print("")
        quit()
```

**Comment by JiFish** [comment]
As an alternative you can use Ctrl-C to exit the interpreter in the same way as breaking a program.

**Comment by richpl** [comment]
Apologies for not replying sooner @Nerun about this. I quite obsessive about developing this software when I worked on it a couple if years ago, but haven't really returned to it since except to process PRs. But it's a good idea, I might add it at some point.
