### ISSUE TITLE
Exactly what I've been looking for!

### ISSUE THREAD

**Issue by maksimKorzh** [richpl/PyBasic#22]
It's not an issue, I just wanted to give a feedback!
This interpreter is just awesome!
Thanks for putting time and effort!

**Comment by richpl** [comment]
Very many thanks for the feedback, I appreciate it. In fact, as you can see, a couple of other guys have contributed to the codebase as well and have greatly improved it.

There are a couple of things I'd like to add, but I haven't had much time lately and haven't been actively working on this (apart from the occasional bug fix) for over two years. But at some point ...
