### ISSUE TITLE
string multiplication with *

### ISSUE THREAD

**Issue by ThomasMertes** [richpl/PyBasic#49]
In the example program PyBStartrek.bas is the line:

1413 Q$=" "*192

I did not find a definition for this kind of string multiplication. Neither in the manual of GW-Basic nor in the manuals of QuickBasic, QBasic or TI-99 extended Basic. But maybe I overlooked it.

There is a page about [repeating a string](https://rosettacode.org/wiki/Repeat_a_string) at Rosetta Code. None of the BASIC examples uses * for string multiplication. In almost all BASIC examples a loop is used. In some BASIC examples there is a function for string multiplication:

    BBC BASIC has STRING$(5, "ha")
    PowerBasic has REPEAT$(5, "ha")
    TI-99 Extended BASIC has RPT$("ha", 5)

So my question is: Which historic BASIC defines this kind of string multiplication?

If there is no historic BASIC with * as string multiplications I suggest to rewrite line 1413 of the PyBStartrek.bas example and additionally I suggest also to remove this functionality from PyBasic and writing a syntax error such as:

 ***** [1413] UNEXPECTED SYMBOL "*".

instead.
If there is some historic BASIC with * as string multiplication please tell me such that I can add it to my [Bas7](http://seed7.sourceforge.net/scrshots/bas7.htm) BASIC interpreter (which is also for historic BASIC programs).

**Comment by RetiredWizard** [comment]
I don't know if it makes a difference to you, but APC Megabasic didn't have a huge user base. I pulled this quote from Chris Cochran's current LinkedIn profile:

> I have been involved in software development continuously since 1976. From 1985 to 2000 I personally developed and supported the x86 assembler-based MegaBasic programming language, having several thousand users, including its use by GE/Fanuc in a line of industrial process controllers.

**Comment by ThomasMertes** [comment]
The size of the APC Megabasic user base is not a problem. And the feature will hardly collide with string expressions allowed by other BASIC dialects. I just didn't want to add a feature that was introduced in 2021 by PyBasic or some other modern BASIC interpreter. My focus is on historic / vintage BASIC programs, therefore modern features are not so interesting.

**Comment by richpl** [comment]
So I guess Python duck typing has sort of come to the rescue again! It gave me string concatenation using + for free.

If @RetiredWizard hadn't found an example of a BASIC dialect that uses * for string repetition, then the purist in me would probably think about implementing a block on its use. But if we have an example then I see no reason to stop it. I will add to the ReadMe at some point. Not sure where this version of Star Trek came from, but clearly from a dialect that also supported *, whether it was APC Megabasic or not.

Bigger issue for me is that while trying to port The Oregon Trail I'm finding instances of a timer function (certainly in Chipmunk BASIC). I'm trying to decide if the port is worth the hassle of trying to introduce something similar or whether I can find a workaround.
