### ISSUE TITLE
Add INT command

### ISSUE THREAD

**Issue by swinslow** [richpl/PyBasic#5]
It would be useful to have an `INT` command, which is equivalent to `math.floor` in Python -- it rounds down floating point numbers.

This is particularly useful in combination with `RND` to create random integers: 

```
> 10 PRINT INT(RND * 6) + 1
> RUN
3
> RUN
6
>
```

I'll submit a PR to add this command, and to describe it briefly in the README.

**Comment by richpl** [comment]
No problem, many thanks for contributing
