### ISSUE TITLE
PORT access

### ISSUE THREAD

**Issue by georgestheking** [richpl/PyBasic#58]
How to access physical port and serial port ?

It will be nice to read or write I/O and access serail port.

Best regards
Georges

**Comment by richpl** [comment]
Hi Georges, thanks for the comment.

I could do that, but the design philosophy behind this implementation is that I maintain hardware independence. This means that folk can take PyBasic and adapt it for the hardware on which they want to run it (and lots of people have recently been running it on devices following the Adafruit blog item). If I started adding hardware specific features here then it would make that more difficult for people.

So I'd encourage you to fork the code and have a go at adding support for serial port access yourself, in a way that you see fit.
