### ISSUE TITLE
Corrected pixel values exceed image bit depth

### ISSUE THREAD

**Issue by dataMaster-Kris** [richpl/PyBasic#63]
Hi,

I am using PyBasic to correct illumination variation. For some of my images, the output images from PyBasic exceed the bit depth. Is this allowed by PyBasic? It might be better if PyBasic were to clip outliers before output.

**Comment by richpl** [comment]
Apologies, for some reason I missed this one. I think you are raising an issue regarding a different repo, also called PyBasic (there are a few), but it definitely isn't this one.
