### ISSUE TITLE
 Compatibility for Microsoft Basic and some display based functionality.

### ISSUE THREAD

**Issue by Jeremy-JYL** [richpl/PyBasic#65]
I like this project and I find a github repo: https://github.com/coding-horror/basic-computer-games
But I can't get most of the game work some can load but when executing produce a error. 
For display things maybe add `CLS` and E.T.C.

Or maybe give me some idea of any other BASIC interpreter the run those retro game.

**Comment by Jeremy-JYL** [comment]
I have try this basic on Vice Commodore Emulator which work fine but when I type it in on PyBasic it stuck on the for loop (110) and the line 40

> 10 PRINT TAB(30);"SINE WAVE"
> 20 PRINT TAB(15);"CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY"
> 30 PRINT: PRINT: PRINT: PRINT: PRINT
> 40 REMARKABLE PROGRAM BY DAVID AHL
> 50 B=0
> 100 REM  START LONG LOOP
> 110 FOR T=0 TO 40 STEP .25
> 120 A=INT(26+25*SIN(T))
> 130 PRINT TAB(A);
> 140 IF B=1 THEN 180
> 150 PRINT "CREATIVE"
> 160 B=1
> 170 GOTO 200
> 180 PRINT "COMPUTING"
> 190 B=0
> 200 NEXT T
> 999 END

**Comment by palazzol** [comment]
FYI, .25 is not parsed as a floating point number, but 0.25 works.

**Comment by richpl** [comment]
> FYI, .25 is not parsed as a floating point number, but 0.25 works.

Thanks for pointing that out. I'm not actively supporting this any more and since the code fails gracefully I've simply updated the Readme to point out the need for a zero prefix
